name: survey_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.4

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.0.3
  hive: ^2.2.3
  hive_generator: ^1.1.3
  intl: ^0.17.0
  json_annotation: ^4.6.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
  freezed: ^2.0.4
  build_runner: ^2.1.11
  json_serializable: ^6.3.0



flutter:
  uses-material-design: true
  generate: true
